//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAdminPeritz.ServiceReferenceChess
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="GameList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Game")]
    public class GameList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.Game>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Game : WpfAdminPeritz.ServiceReferenceChess.BaseEntity
    {
        
        private WpfAdminPeritz.ServiceReferenceChess.Player BlackPlayerField;
        
        private WpfAdminPeritz.ServiceReferenceChess.Player BlackPlayerUserIDField;
        
        private System.DateTime GameDateField;
        
        private int GameIDField;
        
        private WpfAdminPeritz.ServiceReferenceChess.Player ResultField;
        
        private WpfAdminPeritz.ServiceReferenceChess.Player WhitePlayerField;
        
        private WpfAdminPeritz.ServiceReferenceChess.Player WhitePlayerUserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player BlackPlayer
        {
            get
            {
                return this.BlackPlayerField;
            }
            set
            {
                this.BlackPlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player BlackPlayerUserID
        {
            get
            {
                return this.BlackPlayerUserIDField;
            }
            set
            {
                this.BlackPlayerUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GameDate
        {
            get
            {
                return this.GameDateField;
            }
            set
            {
                this.GameDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID
        {
            get
            {
                return this.GameIDField;
            }
            set
            {
                this.GameIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player WhitePlayer
        {
            get
            {
                return this.WhitePlayerField;
            }
            set
            {
                this.WhitePlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player WhitePlayerUserID
        {
            get
            {
                return this.WhitePlayerUserIDField;
            }
            set
            {
                this.WhitePlayerUserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.Player))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.MoveRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.Friendship))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.Game))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Player : WpfAdminPeritz.ServiceReferenceChess.BaseEntity
    {
        
        private System.DateTime DateJoinedField;
        
        private int DrawsField;
        
        private string EmailField;
        
        private int GamesPlayedField;
        
        private string GoogleIdField;
        
        private int LossesField;
        
        private string UserNameField;
        
        private string UserTypeField;
        
        private int WinsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateJoined
        {
            get
            {
                return this.DateJoinedField;
            }
            set
            {
                this.DateJoinedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Draws
        {
            get
            {
                return this.DrawsField;
            }
            set
            {
                this.DrawsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GamesPlayed
        {
            get
            {
                return this.GamesPlayedField;
            }
            set
            {
                this.GamesPlayedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleId
        {
            get
            {
                return this.GoogleIdField;
            }
            set
            {
                this.GoogleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Losses
        {
            get
            {
                return this.LossesField;
            }
            set
            {
                this.LossesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins
        {
            get
            {
                return this.WinsField;
            }
            set
            {
                this.WinsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoveRecord", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class MoveRecord : WpfAdminPeritz.ServiceReferenceChess.BaseEntity
    {
        
        private string FromField;
        
        private WpfAdminPeritz.ServiceReferenceChess.Game GameField;
        
        private int GameIDField;
        
        private int MoveIndexField;
        
        private string MoveTypeField;
        
        private string PromotionField;
        
        private string ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Game Game
        {
            get
            {
                return this.GameField;
            }
            set
            {
                this.GameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID
        {
            get
            {
                return this.GameIDField;
            }
            set
            {
                this.GameIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MoveIndex
        {
            get
            {
                return this.MoveIndexField;
            }
            set
            {
                this.MoveIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoveType
        {
            get
            {
                return this.MoveTypeField;
            }
            set
            {
                this.MoveTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Promotion
        {
            get
            {
                return this.PromotionField;
            }
            set
            {
                this.PromotionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Friendship", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Friendship : WpfAdminPeritz.ServiceReferenceChess.BaseEntity
    {
        
        private System.Nullable<System.DateTime> FriendshipDateField;
        
        private bool IsAcceptedField;
        
        private int ReceiverIDField;
        
        private int RequesterIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FriendshipDate
        {
            get
            {
                return this.FriendshipDateField;
            }
            set
            {
                this.FriendshipDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAccepted
        {
            get
            {
                return this.IsAcceptedField;
            }
            set
            {
                this.IsAcceptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiverID
        {
            get
            {
                return this.ReceiverIDField;
            }
            set
            {
                this.ReceiverIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequesterID
        {
            get
            {
                return this.RequesterIDField;
            }
            set
            {
                this.RequesterIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MoveList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="MoveRecord")]
    public class MoveList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.MoveRecord>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PlayerList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Player")]
    public class PlayerList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.Player>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FriendshipList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Friendship")]
    public class FriendshipList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.Friendship>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WpfAdminPeritz.ServiceReferenceChess.IChessServiceAdmin")]
    public interface IChessServiceAdmin
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllGames", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllGamesResponse")]
        WpfAdminPeritz.ServiceReferenceChess.GameList GetAllGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetGameByID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetGameByIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game GetGameByID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertGameResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game InsertGame(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertGameAndReturn", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertGameAndReturnResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game InsertGameAndReturn(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateGameResponse")]
        void UpdateGame(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateGameResult", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateGameResultResponse")]
        void UpdateGameResult(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteGameResponse")]
        void DeleteGame(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetGamesByPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetGamesByPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceChess.GameList GetGamesByPlayer(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetLatestGameForPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetLatestGameForPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game GetLatestGameForPlayer(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/IsGameFinished", ReplyAction="http://tempuri.org/IChessServiceAdmin/IsGameFinishedResponse")]
        bool IsGameFinished(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetActiveGames", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetActiveGamesResponse")]
        WpfAdminPeritz.ServiceReferenceChess.GameList GetActiveGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertMoveResponse")]
        void InsertMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateMoveResponse")]
        void UpdateMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteMoveResponse")]
        void DeleteMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteMovesByGameIDResponse")]
        void DeleteMovesByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllMoves", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllMovesResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveList GetAllMoves();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetMovesByGameIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetMovesByPlayerID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetMovesByPlayerIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByPlayerID(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/ReturnLastMoveByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/ReturnLastMoveByGameIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveRecord ReturnLastMoveByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UndoLastMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/UndoLastMoveResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveRecord UndoLastMove(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllUsers", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllUsersResponse")]
        WpfAdminPeritz.ServiceReferenceChess.PlayerList GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllplayers", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllplayersResponse")]
        WpfAdminPeritz.ServiceReferenceChess.PlayerList GetAllplayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetUserByID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetUserByIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Player GetUserByID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetUserByName", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetUserByNameResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Player GetUserByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SearchUsersByName", ReplyAction="http://tempuri.org/IChessServiceAdmin/SearchUsersByNameResponse")]
        WpfAdminPeritz.ServiceReferenceChess.PlayerList SearchUsersByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertUserResponse")]
        void InsertUser(WpfAdminPeritz.ServiceReferenceChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateUserResponse")]
        void UpdateUser(WpfAdminPeritz.ServiceReferenceChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteUserResponse")]
        void DeleteUser(WpfAdminPeritz.ServiceReferenceChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeletePlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeletePlayerResponse")]
        void DeletePlayer(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayerStats", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerStatsResponse")]
        void UpdatePlayerStats(int playerID, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayerDraw", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerDrawResponse")]
        void UpdatePlayerDraw(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/RevertPlayerStats", ReplyAction="http://tempuri.org/IChessServiceAdmin/RevertPlayerStatsResponse")]
        void RevertPlayerStats(int playerID, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/RevertPlayerDraw", ReplyAction="http://tempuri.org/IChessServiceAdmin/RevertPlayerDrawResponse")]
        void RevertPlayerDraw(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/IsPlayerTurn", ReplyAction="http://tempuri.org/IChessServiceAdmin/IsPlayerTurnResponse")]
        bool IsPlayerTurn(int gameID, int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SignIn", ReplyAction="http://tempuri.org/IChessServiceAdmin/SignInResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Player SignIn(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllFriendships", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllFriendshipsResponse")]
        WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAllFriendships();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAcceptedFriendsByUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAcceptedFriendsByUserResponse")]
        WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAcceptedFriendsByUser(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetPendingFriendRequestsForUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetPendingFriendRequestsForUserResponse")]
        WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetPendingFriendRequestsForUser(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/FriendshipExists", ReplyAction="http://tempuri.org/IChessServiceAdmin/FriendshipExistsResponse")]
        bool FriendshipExists(int userA, int userB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SendFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/SendFriendRequestResponse")]
        int SendFriendRequest(int requesterID, int receiverID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/AcceptFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/AcceptFriendRequestResponse")]
        void AcceptFriendRequest(int friendshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteFriendship", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteFriendshipResponse")]
        void DeleteFriendship(int friendshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeclineFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeclineFriendRequestResponse")]
        void DeclineFriendRequest(int friendshipID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChessServiceAdminChannel : WpfAdminPeritz.ServiceReferenceChess.IChessServiceAdmin, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChessServiceAdminClient : System.ServiceModel.ClientBase<WpfAdminPeritz.ServiceReferenceChess.IChessServiceAdmin>, WpfAdminPeritz.ServiceReferenceChess.IChessServiceAdmin
    {
        
        public ChessServiceAdminClient()
        {
        }
        
        public ChessServiceAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ChessServiceAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ChessServiceAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ChessServiceAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.GameList GetAllGames()
        {
            return base.Channel.GetAllGames();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game GetGameByID(int gameID)
        {
            return base.Channel.GetGameByID(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game InsertGame(WpfAdminPeritz.ServiceReferenceChess.Game game)
        {
            return base.Channel.InsertGame(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game InsertGameAndReturn(WpfAdminPeritz.ServiceReferenceChess.Game game)
        {
            return base.Channel.InsertGameAndReturn(game);
        }
        
        public void UpdateGame(WpfAdminPeritz.ServiceReferenceChess.Game game)
        {
            base.Channel.UpdateGame(game);
        }
        
        public void UpdateGameResult(WpfAdminPeritz.ServiceReferenceChess.Game game)
        {
            base.Channel.UpdateGameResult(game);
        }
        
        public void DeleteGame(WpfAdminPeritz.ServiceReferenceChess.Game game)
        {
            base.Channel.DeleteGame(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.GameList GetGamesByPlayer(int playerID)
        {
            return base.Channel.GetGamesByPlayer(playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game GetLatestGameForPlayer(int playerID)
        {
            return base.Channel.GetLatestGameForPlayer(playerID);
        }
        
        public bool IsGameFinished(int gameID)
        {
            return base.Channel.IsGameFinished(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.GameList GetActiveGames()
        {
            return base.Channel.GetActiveGames();
        }
        
        public void InsertMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move)
        {
            base.Channel.InsertMove(move);
        }
        
        public void UpdateMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move)
        {
            base.Channel.UpdateMove(move);
        }
        
        public void DeleteMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move)
        {
            base.Channel.DeleteMove(move);
        }
        
        public void DeleteMovesByGameID(int gameID)
        {
            base.Channel.DeleteMovesByGameID(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveList GetAllMoves()
        {
            return base.Channel.GetAllMoves();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByGameID(int gameID)
        {
            return base.Channel.GetMovesByGameID(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByPlayerID(int playerID)
        {
            return base.Channel.GetMovesByPlayerID(playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveRecord ReturnLastMoveByGameID(int gameID)
        {
            return base.Channel.ReturnLastMoveByGameID(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveRecord UndoLastMove(int gameID)
        {
            return base.Channel.UndoLastMove(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.PlayerList GetAllUsers()
        {
            return base.Channel.GetAllUsers();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.PlayerList GetAllplayers()
        {
            return base.Channel.GetAllplayers();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Player GetUserByID(int userID)
        {
            return base.Channel.GetUserByID(userID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Player GetUserByName(string name)
        {
            return base.Channel.GetUserByName(name);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.PlayerList SearchUsersByName(string name)
        {
            return base.Channel.SearchUsersByName(name);
        }
        
        public void InsertUser(WpfAdminPeritz.ServiceReferenceChess.Player user)
        {
            base.Channel.InsertUser(user);
        }
        
        public void UpdateUser(WpfAdminPeritz.ServiceReferenceChess.Player user)
        {
            base.Channel.UpdateUser(user);
        }
        
        public void DeleteUser(WpfAdminPeritz.ServiceReferenceChess.Player user)
        {
            base.Channel.DeleteUser(user);
        }
        
        public void DeletePlayer(WpfAdminPeritz.ServiceReferenceChess.Player player)
        {
            base.Channel.DeletePlayer(player);
        }
        
        public void UpdatePlayerStats(int playerID, bool won)
        {
            base.Channel.UpdatePlayerStats(playerID, won);
        }
        
        public void UpdatePlayerDraw(int playerID)
        {
            base.Channel.UpdatePlayerDraw(playerID);
        }
        
        public void RevertPlayerStats(int playerID, bool won)
        {
            base.Channel.RevertPlayerStats(playerID, won);
        }
        
        public void RevertPlayerDraw(int playerID)
        {
            base.Channel.RevertPlayerDraw(playerID);
        }
        
        public bool IsPlayerTurn(int gameID, int playerID)
        {
            return base.Channel.IsPlayerTurn(gameID, playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Player SignIn(string email, string password)
        {
            return base.Channel.SignIn(email, password);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAllFriendships()
        {
            return base.Channel.GetAllFriendships();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAcceptedFriendsByUser(int userID)
        {
            return base.Channel.GetAcceptedFriendsByUser(userID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetPendingFriendRequestsForUser(int userID)
        {
            return base.Channel.GetPendingFriendRequestsForUser(userID);
        }
        
        public bool FriendshipExists(int userA, int userB)
        {
            return base.Channel.FriendshipExists(userA, userB);
        }
        
        public int SendFriendRequest(int requesterID, int receiverID)
        {
            return base.Channel.SendFriendRequest(requesterID, receiverID);
        }
        
        public void AcceptFriendRequest(int friendshipID)
        {
            base.Channel.AcceptFriendRequest(friendshipID);
        }
        
        public void DeleteFriendship(int friendshipID)
        {
            base.Channel.DeleteFriendship(friendshipID);
        }
        
        public void DeclineFriendRequest(int friendshipID)
        {
            base.Channel.DeclineFriendRequest(friendshipID);
        }
    }
}
