//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAdminPeritz.ServiceReferenceChess {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="GameList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Game")]
    [System.SerializableAttribute()]
    public class GameList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.Game> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Game : WpfAdminPeritz.ServiceReferenceChess.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAdminPeritz.ServiceReferenceChess.Player BlackPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GameDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAdminPeritz.ServiceReferenceChess.Player ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAdminPeritz.ServiceReferenceChess.Player WhitePlayerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player BlackPlayer {
            get {
                return this.BlackPlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.BlackPlayerField, value) != true)) {
                    this.BlackPlayerField = value;
                    this.RaisePropertyChanged("BlackPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GameDate {
            get {
                return this.GameDateField;
            }
            set {
                if ((this.GameDateField.Equals(value) != true)) {
                    this.GameDateField = value;
                    this.RaisePropertyChanged("GameDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player WhitePlayer {
            get {
                return this.WhitePlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.WhitePlayerField, value) != true)) {
                    this.WhitePlayerField = value;
                    this.RaisePropertyChanged("WhitePlayer");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.Player))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.MoveRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.Friendship))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.Game))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Player : WpfAdminPeritz.ServiceReferenceChess.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateJoinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GamesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoogleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LossesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateJoined {
            get {
                return this.DateJoinedField;
            }
            set {
                if ((this.DateJoinedField.Equals(value) != true)) {
                    this.DateJoinedField = value;
                    this.RaisePropertyChanged("DateJoined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Draws {
            get {
                return this.DrawsField;
            }
            set {
                if ((this.DrawsField.Equals(value) != true)) {
                    this.DrawsField = value;
                    this.RaisePropertyChanged("Draws");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GamesPlayed {
            get {
                return this.GamesPlayedField;
            }
            set {
                if ((this.GamesPlayedField.Equals(value) != true)) {
                    this.GamesPlayedField = value;
                    this.RaisePropertyChanged("GamesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleId {
            get {
                return this.GoogleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleIdField, value) != true)) {
                    this.GoogleIdField = value;
                    this.RaisePropertyChanged("GoogleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Losses {
            get {
                return this.LossesField;
            }
            set {
                if ((this.LossesField.Equals(value) != true)) {
                    this.LossesField = value;
                    this.RaisePropertyChanged("Losses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoveRecord", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class MoveRecord : WpfAdminPeritz.ServiceReferenceChess.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAdminPeritz.ServiceReferenceChess.Game GameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MoveIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoveTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromotionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Game Game {
            get {
                return this.GameField;
            }
            set {
                if ((object.ReferenceEquals(this.GameField, value) != true)) {
                    this.GameField = value;
                    this.RaisePropertyChanged("Game");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MoveIndex {
            get {
                return this.MoveIndexField;
            }
            set {
                if ((this.MoveIndexField.Equals(value) != true)) {
                    this.MoveIndexField = value;
                    this.RaisePropertyChanged("MoveIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoveType {
            get {
                return this.MoveTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MoveTypeField, value) != true)) {
                    this.MoveTypeField = value;
                    this.RaisePropertyChanged("MoveType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Promotion {
            get {
                return this.PromotionField;
            }
            set {
                if ((object.ReferenceEquals(this.PromotionField, value) != true)) {
                    this.PromotionField = value;
                    this.RaisePropertyChanged("Promotion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Friendship", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Friendship : WpfAdminPeritz.ServiceReferenceChess.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FriendshipDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAcceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAdminPeritz.ServiceReferenceChess.Player ReceiverIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAdminPeritz.ServiceReferenceChess.Player RequesterIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FriendshipDate {
            get {
                return this.FriendshipDateField;
            }
            set {
                if ((this.FriendshipDateField.Equals(value) != true)) {
                    this.FriendshipDateField = value;
                    this.RaisePropertyChanged("FriendshipDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAccepted {
            get {
                return this.IsAcceptedField;
            }
            set {
                if ((this.IsAcceptedField.Equals(value) != true)) {
                    this.IsAcceptedField = value;
                    this.RaisePropertyChanged("IsAccepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player ReceiverID {
            get {
                return this.ReceiverIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverIDField, value) != true)) {
                    this.ReceiverIDField = value;
                    this.RaisePropertyChanged("ReceiverID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player RequesterID {
            get {
                return this.RequesterIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterIDField, value) != true)) {
                    this.RequesterIDField = value;
                    this.RaisePropertyChanged("RequesterID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MoveList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="MoveRecord")]
    [System.SerializableAttribute()]
    public class MoveList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.MoveRecord> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PlayerList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Player")]
    [System.SerializableAttribute()]
    public class PlayerList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.Player> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FriendshipList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Friendship")]
    [System.SerializableAttribute()]
    public class FriendshipList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.Friendship> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceChess.IChessServiceAdmin")]
    public interface IChessServiceAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllGames", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllGamesResponse")]
        WpfAdminPeritz.ServiceReferenceChess.GameList GetAllGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllGames", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllGamesResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.GameList> GetAllGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetGameByID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetGameByIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game GetGameByID(WpfAdminPeritz.ServiceReferenceChess.Game gameI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetGameByID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetGameByIDResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> GetGameByIDAsync(WpfAdminPeritz.ServiceReferenceChess.Game gameI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertGameResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game InsertGame(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertGameResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> InsertGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateGameResponse")]
        void UpdateGame(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateGameResponse")]
        System.Threading.Tasks.Task UpdateGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteGameResponse")]
        void DeleteGame(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteGameResponse")]
        System.Threading.Tasks.Task DeleteGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetGamesByPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetGamesByPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceChess.GameList GetGamesByPlayer(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetGamesByPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetGamesByPlayerResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.GameList> GetGamesByPlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetLatestGameForPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetLatestGameForPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game GetLatestGameForPlayer(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetLatestGameForPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetLatestGameForPlayerResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> GetLatestGameForPlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/IsGameFinished", ReplyAction="http://tempuri.org/IChessServiceAdmin/IsGameFinishedResponse")]
        bool IsGameFinished(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/IsGameFinished", ReplyAction="http://tempuri.org/IChessServiceAdmin/IsGameFinishedResponse")]
        System.Threading.Tasks.Task<bool> IsGameFinishedAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertMoveResponse")]
        void InsertMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertMoveResponse")]
        System.Threading.Tasks.Task InsertMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateMoveResponse")]
        void UpdateMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateMoveResponse")]
        System.Threading.Tasks.Task UpdateMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteMoveResponse")]
        void DeleteMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteMoveResponse")]
        System.Threading.Tasks.Task DeleteMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteMovesByGameIDResponse")]
        void DeleteMovesByGameID(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteMovesByGameIDResponse")]
        System.Threading.Tasks.Task DeleteMovesByGameIDAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetMovesByGameIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByGameID(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetMovesByGameIDResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveList> GetMovesByGameIDAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetMovesByPlayerID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetMovesByPlayerIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByPlayerID(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetMovesByPlayerID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetMovesByPlayerIDResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveList> GetMovesByPlayerIDAsync(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/ReturnLastMoveByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/ReturnLastMoveByGameIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveRecord ReturnLastMoveByGameID(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/ReturnLastMoveByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/ReturnLastMoveByGameIDResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveRecord> ReturnLastMoveByGameIDAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UndoLastMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/UndoLastMoveResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveRecord UndoLastMove(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UndoLastMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/UndoLastMoveResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveRecord> UndoLastMoveAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllplayers", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllplayersResponse")]
        WpfAdminPeritz.ServiceReferenceChess.PlayerList GetAllplayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllplayers", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllplayersResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.PlayerList> GetAllplayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetPlayerByID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetPlayerByIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Player GetPlayerByID(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetPlayerByID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetPlayerByIDResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> GetPlayerByIDAsync(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetPlayerByName", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetPlayerByNameResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Player GetPlayerByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetPlayerByName", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetPlayerByNameResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> GetPlayerByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SearchplayersByName", ReplyAction="http://tempuri.org/IChessServiceAdmin/SearchplayersByNameResponse")]
        WpfAdminPeritz.ServiceReferenceChess.PlayerList SearchplayersByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SearchplayersByName", ReplyAction="http://tempuri.org/IChessServiceAdmin/SearchplayersByNameResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.PlayerList> SearchplayersByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertPlayerResponse")]
        void InsertPlayer(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertPlayerResponse")]
        System.Threading.Tasks.Task InsertPlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerResponse")]
        void UpdatePlayer(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerResponse")]
        System.Threading.Tasks.Task UpdatePlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeletePlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeletePlayerResponse")]
        void DeletePlayer(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeletePlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeletePlayerResponse")]
        System.Threading.Tasks.Task DeletePlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayerStats", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerStatsResponse")]
        void UpdatePlayerStats(WpfAdminPeritz.ServiceReferenceChess.Player player, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayerStats", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerStatsResponse")]
        System.Threading.Tasks.Task UpdatePlayerStatsAsync(WpfAdminPeritz.ServiceReferenceChess.Player player, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayerDraw", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerDrawResponse")]
        void UpdatePlayerDraw(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayerDraw", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerDrawResponse")]
        System.Threading.Tasks.Task UpdatePlayerDrawAsync(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/RevertPlayerStats", ReplyAction="http://tempuri.org/IChessServiceAdmin/RevertPlayerStatsResponse")]
        void RevertPlayerStats(WpfAdminPeritz.ServiceReferenceChess.Player player, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/RevertPlayerStats", ReplyAction="http://tempuri.org/IChessServiceAdmin/RevertPlayerStatsResponse")]
        System.Threading.Tasks.Task RevertPlayerStatsAsync(WpfAdminPeritz.ServiceReferenceChess.Player player, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/RevertPlayerDraw", ReplyAction="http://tempuri.org/IChessServiceAdmin/RevertPlayerDrawResponse")]
        void RevertPlayerDraw(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/RevertPlayerDraw", ReplyAction="http://tempuri.org/IChessServiceAdmin/RevertPlayerDrawResponse")]
        System.Threading.Tasks.Task RevertPlayerDrawAsync(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/IsPlayerTurn", ReplyAction="http://tempuri.org/IChessServiceAdmin/IsPlayerTurnResponse")]
        bool IsPlayerTurn(WpfAdminPeritz.ServiceReferenceChess.Game game, WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/IsPlayerTurn", ReplyAction="http://tempuri.org/IChessServiceAdmin/IsPlayerTurnResponse")]
        System.Threading.Tasks.Task<bool> IsPlayerTurnAsync(WpfAdminPeritz.ServiceReferenceChess.Game game, WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SignIn", ReplyAction="http://tempuri.org/IChessServiceAdmin/SignInResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Player SignIn(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SignIn", ReplyAction="http://tempuri.org/IChessServiceAdmin/SignInResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> SignInAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllFriendships", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllFriendshipsResponse")]
        WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAllFriendships();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllFriendships", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllFriendshipsResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetAllFriendshipsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAcceptedFriendsByPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAcceptedFriendsByPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAcceptedFriendsByPlayer(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAcceptedFriendsByPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAcceptedFriendsByPlayerResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetAcceptedFriendsByPlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetPendingFriendRequestsForPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetPendingFriendRequestsForPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetPendingFriendRequestsForPlayer(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetPendingFriendRequestsForPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetPendingFriendRequestsForPlayerResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetPendingFriendRequestsForPlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SendFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/SendFriendRequestResponse")]
        int SendFriendRequest(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SendFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<int> SendFriendRequestAsync(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/AcceptFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/AcceptFriendRequestResponse")]
        void AcceptFriendRequest(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/AcceptFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task AcceptFriendRequestAsync(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteFriendship", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteFriendshipResponse")]
        void DeleteFriendship(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteFriendship", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteFriendshipResponse")]
        System.Threading.Tasks.Task DeleteFriendshipAsync(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeclineFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeclineFriendRequestResponse")]
        void DeclineFriendRequest(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeclineFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeclineFriendRequestResponse")]
        System.Threading.Tasks.Task DeclineFriendRequestAsync(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChessServiceAdminChannel : WpfAdminPeritz.ServiceReferenceChess.IChessServiceAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChessServiceAdminClient : System.ServiceModel.ClientBase<WpfAdminPeritz.ServiceReferenceChess.IChessServiceAdmin>, WpfAdminPeritz.ServiceReferenceChess.IChessServiceAdmin {
        
        public ChessServiceAdminClient() {
        }
        
        public ChessServiceAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChessServiceAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChessServiceAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChessServiceAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.GameList GetAllGames() {
            return base.Channel.GetAllGames();
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.GameList> GetAllGamesAsync() {
            return base.Channel.GetAllGamesAsync();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game GetGameByID(WpfAdminPeritz.ServiceReferenceChess.Game gameI) {
            return base.Channel.GetGameByID(gameI);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> GetGameByIDAsync(WpfAdminPeritz.ServiceReferenceChess.Game gameI) {
            return base.Channel.GetGameByIDAsync(gameI);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game InsertGame(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.InsertGame(game);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> InsertGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.InsertGameAsync(game);
        }
        
        public void UpdateGame(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            base.Channel.UpdateGame(game);
        }
        
        public System.Threading.Tasks.Task UpdateGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.UpdateGameAsync(game);
        }
        
        public void DeleteGame(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            base.Channel.DeleteGame(game);
        }
        
        public System.Threading.Tasks.Task DeleteGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.DeleteGameAsync(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.GameList GetGamesByPlayer(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.GetGamesByPlayer(player);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.GameList> GetGamesByPlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.GetGamesByPlayerAsync(player);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game GetLatestGameForPlayer(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.GetLatestGameForPlayer(player);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> GetLatestGameForPlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.GetLatestGameForPlayerAsync(player);
        }
        
        public bool IsGameFinished(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.IsGameFinished(game);
        }
        
        public System.Threading.Tasks.Task<bool> IsGameFinishedAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.IsGameFinishedAsync(game);
        }
        
        public void InsertMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            base.Channel.InsertMove(move);
        }
        
        public System.Threading.Tasks.Task InsertMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            return base.Channel.InsertMoveAsync(move);
        }
        
        public void UpdateMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            base.Channel.UpdateMove(move);
        }
        
        public System.Threading.Tasks.Task UpdateMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            return base.Channel.UpdateMoveAsync(move);
        }
        
        public void DeleteMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            base.Channel.DeleteMove(move);
        }
        
        public System.Threading.Tasks.Task DeleteMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            return base.Channel.DeleteMoveAsync(move);
        }
        
        public void DeleteMovesByGameID(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            base.Channel.DeleteMovesByGameID(game);
        }
        
        public System.Threading.Tasks.Task DeleteMovesByGameIDAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.DeleteMovesByGameIDAsync(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByGameID(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.GetMovesByGameID(game);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveList> GetMovesByGameIDAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.GetMovesByGameIDAsync(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByPlayerID(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.GetMovesByPlayerID(player);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveList> GetMovesByPlayerIDAsync(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.GetMovesByPlayerIDAsync(player);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveRecord ReturnLastMoveByGameID(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.ReturnLastMoveByGameID(game);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveRecord> ReturnLastMoveByGameIDAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.ReturnLastMoveByGameIDAsync(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveRecord UndoLastMove(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.UndoLastMove(game);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveRecord> UndoLastMoveAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.UndoLastMoveAsync(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.PlayerList GetAllplayers() {
            return base.Channel.GetAllplayers();
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.PlayerList> GetAllplayersAsync() {
            return base.Channel.GetAllplayersAsync();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Player GetPlayerByID(int playerID) {
            return base.Channel.GetPlayerByID(playerID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> GetPlayerByIDAsync(int playerID) {
            return base.Channel.GetPlayerByIDAsync(playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Player GetPlayerByName(string name) {
            return base.Channel.GetPlayerByName(name);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> GetPlayerByNameAsync(string name) {
            return base.Channel.GetPlayerByNameAsync(name);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.PlayerList SearchplayersByName(string name) {
            return base.Channel.SearchplayersByName(name);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.PlayerList> SearchplayersByNameAsync(string name) {
            return base.Channel.SearchplayersByNameAsync(name);
        }
        
        public void InsertPlayer(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            base.Channel.InsertPlayer(player);
        }
        
        public System.Threading.Tasks.Task InsertPlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.InsertPlayerAsync(player);
        }
        
        public void UpdatePlayer(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            base.Channel.UpdatePlayer(player);
        }
        
        public System.Threading.Tasks.Task UpdatePlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.UpdatePlayerAsync(player);
        }
        
        public void DeletePlayer(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            base.Channel.DeletePlayer(player);
        }
        
        public System.Threading.Tasks.Task DeletePlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.DeletePlayerAsync(player);
        }
        
        public void UpdatePlayerStats(WpfAdminPeritz.ServiceReferenceChess.Player player, bool won) {
            base.Channel.UpdatePlayerStats(player, won);
        }
        
        public System.Threading.Tasks.Task UpdatePlayerStatsAsync(WpfAdminPeritz.ServiceReferenceChess.Player player, bool won) {
            return base.Channel.UpdatePlayerStatsAsync(player, won);
        }
        
        public void UpdatePlayerDraw(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            base.Channel.UpdatePlayerDraw(player);
        }
        
        public System.Threading.Tasks.Task UpdatePlayerDrawAsync(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.UpdatePlayerDrawAsync(player);
        }
        
        public void RevertPlayerStats(WpfAdminPeritz.ServiceReferenceChess.Player player, bool won) {
            base.Channel.RevertPlayerStats(player, won);
        }
        
        public System.Threading.Tasks.Task RevertPlayerStatsAsync(WpfAdminPeritz.ServiceReferenceChess.Player player, bool won) {
            return base.Channel.RevertPlayerStatsAsync(player, won);
        }
        
        public void RevertPlayerDraw(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            base.Channel.RevertPlayerDraw(player);
        }
        
        public System.Threading.Tasks.Task RevertPlayerDrawAsync(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.RevertPlayerDrawAsync(player);
        }
        
        public bool IsPlayerTurn(WpfAdminPeritz.ServiceReferenceChess.Game game, WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.IsPlayerTurn(game, player);
        }
        
        public System.Threading.Tasks.Task<bool> IsPlayerTurnAsync(WpfAdminPeritz.ServiceReferenceChess.Game game, WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.IsPlayerTurnAsync(game, player);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Player SignIn(string email, string password) {
            return base.Channel.SignIn(email, password);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> SignInAsync(string email, string password) {
            return base.Channel.SignInAsync(email, password);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAllFriendships() {
            return base.Channel.GetAllFriendships();
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetAllFriendshipsAsync() {
            return base.Channel.GetAllFriendshipsAsync();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAcceptedFriendsByPlayer(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.GetAcceptedFriendsByPlayer(player);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetAcceptedFriendsByPlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.GetAcceptedFriendsByPlayerAsync(player);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetPendingFriendRequestsForPlayer(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.GetPendingFriendRequestsForPlayer(player);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetPendingFriendRequestsForPlayerAsync(WpfAdminPeritz.ServiceReferenceChess.Player player) {
            return base.Channel.GetPendingFriendRequestsForPlayerAsync(player);
        }
        
        public int SendFriendRequest(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship) {
            return base.Channel.SendFriendRequest(friendship);
        }
        
        public System.Threading.Tasks.Task<int> SendFriendRequestAsync(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship) {
            return base.Channel.SendFriendRequestAsync(friendship);
        }
        
        public void AcceptFriendRequest(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship) {
            base.Channel.AcceptFriendRequest(friendship);
        }
        
        public System.Threading.Tasks.Task AcceptFriendRequestAsync(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship) {
            return base.Channel.AcceptFriendRequestAsync(friendship);
        }
        
        public void DeleteFriendship(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship) {
            base.Channel.DeleteFriendship(friendship);
        }
        
        public System.Threading.Tasks.Task DeleteFriendshipAsync(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship) {
            return base.Channel.DeleteFriendshipAsync(friendship);
        }
        
        public void DeclineFriendRequest(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship) {
            base.Channel.DeclineFriendRequest(friendship);
        }
        
        public System.Threading.Tasks.Task DeclineFriendRequestAsync(WpfAdminPeritz.ServiceReferenceChess.Friendship friendship) {
            return base.Channel.DeclineFriendRequestAsync(friendship);
        }
    }
}
