//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAdminPeritz.ServiceReferenceChess {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="GameList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Game")]
    [System.SerializableAttribute()]
    public class GameList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.Game> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Game : WpfAdminPeritz.ServiceReferenceChess.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAdminPeritz.ServiceReferenceChess.Player BlackPlayerUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GameDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAdminPeritz.ServiceReferenceChess.Player ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAdminPeritz.ServiceReferenceChess.Player WhitePlayerUserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player BlackPlayerUserID {
            get {
                return this.BlackPlayerUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BlackPlayerUserIDField, value) != true)) {
                    this.BlackPlayerUserIDField = value;
                    this.RaisePropertyChanged("BlackPlayerUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GameDate {
            get {
                return this.GameDateField;
            }
            set {
                if ((this.GameDateField.Equals(value) != true)) {
                    this.GameDateField = value;
                    this.RaisePropertyChanged("GameDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID {
            get {
                return this.GameIDField;
            }
            set {
                if ((this.GameIDField.Equals(value) != true)) {
                    this.GameIDField = value;
                    this.RaisePropertyChanged("GameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceChess.Player WhitePlayerUserID {
            get {
                return this.WhitePlayerUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WhitePlayerUserIDField, value) != true)) {
                    this.WhitePlayerUserIDField = value;
                    this.RaisePropertyChanged("WhitePlayerUserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.Player))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.MoveRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.Friendship))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceChess.Game))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Player : WpfAdminPeritz.ServiceReferenceChess.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateJoinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GamesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LossesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateJoined {
            get {
                return this.DateJoinedField;
            }
            set {
                if ((this.DateJoinedField.Equals(value) != true)) {
                    this.DateJoinedField = value;
                    this.RaisePropertyChanged("DateJoined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Draws {
            get {
                return this.DrawsField;
            }
            set {
                if ((this.DrawsField.Equals(value) != true)) {
                    this.DrawsField = value;
                    this.RaisePropertyChanged("Draws");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GamesPlayed {
            get {
                return this.GamesPlayedField;
            }
            set {
                if ((this.GamesPlayedField.Equals(value) != true)) {
                    this.GamesPlayedField = value;
                    this.RaisePropertyChanged("GamesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Losses {
            get {
                return this.LossesField;
            }
            set {
                if ((this.LossesField.Equals(value) != true)) {
                    this.LossesField = value;
                    this.RaisePropertyChanged("Losses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoveRecord", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class MoveRecord : WpfAdminPeritz.ServiceReferenceChess.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MoveIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoveTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromotionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID {
            get {
                return this.GameIDField;
            }
            set {
                if ((this.GameIDField.Equals(value) != true)) {
                    this.GameIDField = value;
                    this.RaisePropertyChanged("GameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MoveIndex {
            get {
                return this.MoveIndexField;
            }
            set {
                if ((this.MoveIndexField.Equals(value) != true)) {
                    this.MoveIndexField = value;
                    this.RaisePropertyChanged("MoveIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoveType {
            get {
                return this.MoveTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MoveTypeField, value) != true)) {
                    this.MoveTypeField = value;
                    this.RaisePropertyChanged("MoveType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Promotion {
            get {
                return this.PromotionField;
            }
            set {
                if ((object.ReferenceEquals(this.PromotionField, value) != true)) {
                    this.PromotionField = value;
                    this.RaisePropertyChanged("Promotion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Friendship", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Friendship : WpfAdminPeritz.ServiceReferenceChess.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FriendshipDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAcceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiverIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequesterIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FriendshipDate {
            get {
                return this.FriendshipDateField;
            }
            set {
                if ((this.FriendshipDateField.Equals(value) != true)) {
                    this.FriendshipDateField = value;
                    this.RaisePropertyChanged("FriendshipDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAccepted {
            get {
                return this.IsAcceptedField;
            }
            set {
                if ((this.IsAcceptedField.Equals(value) != true)) {
                    this.IsAcceptedField = value;
                    this.RaisePropertyChanged("IsAccepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiverID {
            get {
                return this.ReceiverIDField;
            }
            set {
                if ((this.ReceiverIDField.Equals(value) != true)) {
                    this.ReceiverIDField = value;
                    this.RaisePropertyChanged("ReceiverID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequesterID {
            get {
                return this.RequesterIDField;
            }
            set {
                if ((this.RequesterIDField.Equals(value) != true)) {
                    this.RequesterIDField = value;
                    this.RaisePropertyChanged("RequesterID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MoveList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="MoveRecord")]
    [System.SerializableAttribute()]
    public class MoveList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.MoveRecord> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PlayerList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Player")]
    [System.SerializableAttribute()]
    public class PlayerList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.Player> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FriendshipList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Friendship")]
    [System.SerializableAttribute()]
    public class FriendshipList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceChess.Friendship> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceChess.IChessServiceAdmin")]
    public interface IChessServiceAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllGames", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllGamesResponse")]
        WpfAdminPeritz.ServiceReferenceChess.GameList GetAllGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllGames", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllGamesResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.GameList> GetAllGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetGameByID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetGameByIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game GetGameByID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetGameByID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetGameByIDResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> GetGameByIDAsync(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertGameResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game InsertGame(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertGameResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> InsertGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertGameAndReturn", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertGameAndReturnResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game InsertGameAndReturn(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertGameAndReturn", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertGameAndReturnResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> InsertGameAndReturnAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateGameResponse")]
        void UpdateGame(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateGameResponse")]
        System.Threading.Tasks.Task UpdateGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateGameResult", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateGameResultResponse")]
        void UpdateGameResult(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateGameResult", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateGameResultResponse")]
        System.Threading.Tasks.Task UpdateGameResultAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteGameResponse")]
        void DeleteGame(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteGame", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteGameResponse")]
        System.Threading.Tasks.Task DeleteGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetGamesByPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetGamesByPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceChess.GameList GetGamesByPlayer(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetGamesByPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetGamesByPlayerResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.GameList> GetGamesByPlayerAsync(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetLatestGameForPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetLatestGameForPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Game GetLatestGameForPlayer(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetLatestGameForPlayer", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetLatestGameForPlayerResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> GetLatestGameForPlayerAsync(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/IsGameFinished", ReplyAction="http://tempuri.org/IChessServiceAdmin/IsGameFinishedResponse")]
        bool IsGameFinished(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/IsGameFinished", ReplyAction="http://tempuri.org/IChessServiceAdmin/IsGameFinishedResponse")]
        System.Threading.Tasks.Task<bool> IsGameFinishedAsync(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetActiveGames", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetActiveGamesResponse")]
        WpfAdminPeritz.ServiceReferenceChess.GameList GetActiveGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetActiveGames", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetActiveGamesResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.GameList> GetActiveGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertMoveResponse")]
        void InsertMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertMoveResponse")]
        System.Threading.Tasks.Task InsertMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateMoveResponse")]
        void UpdateMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateMoveResponse")]
        System.Threading.Tasks.Task UpdateMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteMoveResponse")]
        void DeleteMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteMoveResponse")]
        System.Threading.Tasks.Task DeleteMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteMovesByGameIDResponse")]
        void DeleteMovesByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteMovesByGameIDResponse")]
        System.Threading.Tasks.Task DeleteMovesByGameIDAsync(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllMoves", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllMovesResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveList GetAllMoves();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllMoves", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllMovesResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveList> GetAllMovesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetMovesByGameIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetMovesByGameIDResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveList> GetMovesByGameIDAsync(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetMovesByPlayerID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetMovesByPlayerIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByPlayerID(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetMovesByPlayerID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetMovesByPlayerIDResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveList> GetMovesByPlayerIDAsync(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/ReturnLastMoveByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/ReturnLastMoveByGameIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveRecord ReturnLastMoveByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/ReturnLastMoveByGameID", ReplyAction="http://tempuri.org/IChessServiceAdmin/ReturnLastMoveByGameIDResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveRecord> ReturnLastMoveByGameIDAsync(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UndoLastMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/UndoLastMoveResponse")]
        WpfAdminPeritz.ServiceReferenceChess.MoveRecord UndoLastMove(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UndoLastMove", ReplyAction="http://tempuri.org/IChessServiceAdmin/UndoLastMoveResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveRecord> UndoLastMoveAsync(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllUsers", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllUsersResponse")]
        WpfAdminPeritz.ServiceReferenceChess.PlayerList GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllUsers", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllUsersResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.PlayerList> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetUserByID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetUserByIDResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Player GetUserByID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetUserByID", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetUserByIDResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> GetUserByIDAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetUserByName", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetUserByNameResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Player GetUserByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetUserByName", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetUserByNameResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> GetUserByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SearchUsersByName", ReplyAction="http://tempuri.org/IChessServiceAdmin/SearchUsersByNameResponse")]
        WpfAdminPeritz.ServiceReferenceChess.PlayerList SearchUsersByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SearchUsersByName", ReplyAction="http://tempuri.org/IChessServiceAdmin/SearchUsersByNameResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.PlayerList> SearchUsersByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertUserResponse")]
        void InsertUser(WpfAdminPeritz.ServiceReferenceChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/InsertUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/InsertUserResponse")]
        System.Threading.Tasks.Task InsertUserAsync(WpfAdminPeritz.ServiceReferenceChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateUserResponse")]
        void UpdateUser(WpfAdminPeritz.ServiceReferenceChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdateUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(WpfAdminPeritz.ServiceReferenceChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteUserResponse")]
        void DeleteUser(WpfAdminPeritz.ServiceReferenceChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(WpfAdminPeritz.ServiceReferenceChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayerStats", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerStatsResponse")]
        void UpdatePlayerStats(int playerID, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayerStats", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerStatsResponse")]
        System.Threading.Tasks.Task UpdatePlayerStatsAsync(int playerID, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayerDraw", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerDrawResponse")]
        void UpdatePlayerDraw(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/UpdatePlayerDraw", ReplyAction="http://tempuri.org/IChessServiceAdmin/UpdatePlayerDrawResponse")]
        System.Threading.Tasks.Task UpdatePlayerDrawAsync(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/RevertPlayerStats", ReplyAction="http://tempuri.org/IChessServiceAdmin/RevertPlayerStatsResponse")]
        void RevertPlayerStats(int playerID, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/RevertPlayerStats", ReplyAction="http://tempuri.org/IChessServiceAdmin/RevertPlayerStatsResponse")]
        System.Threading.Tasks.Task RevertPlayerStatsAsync(int playerID, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/RevertPlayerDraw", ReplyAction="http://tempuri.org/IChessServiceAdmin/RevertPlayerDrawResponse")]
        void RevertPlayerDraw(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/RevertPlayerDraw", ReplyAction="http://tempuri.org/IChessServiceAdmin/RevertPlayerDrawResponse")]
        System.Threading.Tasks.Task RevertPlayerDrawAsync(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/IsPlayerTurn", ReplyAction="http://tempuri.org/IChessServiceAdmin/IsPlayerTurnResponse")]
        bool IsPlayerTurn(int gameID, int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/IsPlayerTurn", ReplyAction="http://tempuri.org/IChessServiceAdmin/IsPlayerTurnResponse")]
        System.Threading.Tasks.Task<bool> IsPlayerTurnAsync(int gameID, int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SignIn", ReplyAction="http://tempuri.org/IChessServiceAdmin/SignInResponse")]
        WpfAdminPeritz.ServiceReferenceChess.Player SignIn(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SignIn", ReplyAction="http://tempuri.org/IChessServiceAdmin/SignInResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> SignInAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllFriendships", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllFriendshipsResponse")]
        WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAllFriendships();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAllFriendships", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAllFriendshipsResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetAllFriendshipsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAcceptedFriendsByUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAcceptedFriendsByUserResponse")]
        WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAcceptedFriendsByUser(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetAcceptedFriendsByUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetAcceptedFriendsByUserResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetAcceptedFriendsByUserAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetPendingFriendRequestsForUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetPendingFriendRequestsForUserResponse")]
        WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetPendingFriendRequestsForUser(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/GetPendingFriendRequestsForUser", ReplyAction="http://tempuri.org/IChessServiceAdmin/GetPendingFriendRequestsForUserResponse")]
        System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetPendingFriendRequestsForUserAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/FriendshipExists", ReplyAction="http://tempuri.org/IChessServiceAdmin/FriendshipExistsResponse")]
        bool FriendshipExists(int userA, int userB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/FriendshipExists", ReplyAction="http://tempuri.org/IChessServiceAdmin/FriendshipExistsResponse")]
        System.Threading.Tasks.Task<bool> FriendshipExistsAsync(int userA, int userB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SendFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/SendFriendRequestResponse")]
        int SendFriendRequest(int requesterID, int receiverID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/SendFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<int> SendFriendRequestAsync(int requesterID, int receiverID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/AcceptFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/AcceptFriendRequestResponse")]
        void AcceptFriendRequest(int friendshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/AcceptFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task AcceptFriendRequestAsync(int friendshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteFriendship", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteFriendshipResponse")]
        void DeleteFriendship(int friendshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeleteFriendship", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeleteFriendshipResponse")]
        System.Threading.Tasks.Task DeleteFriendshipAsync(int friendshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeclineFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeclineFriendRequestResponse")]
        void DeclineFriendRequest(int friendshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceAdmin/DeclineFriendRequest", ReplyAction="http://tempuri.org/IChessServiceAdmin/DeclineFriendRequestResponse")]
        System.Threading.Tasks.Task DeclineFriendRequestAsync(int friendshipID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChessServiceAdminChannel : WpfAdminPeritz.ServiceReferenceChess.IChessServiceAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChessServiceAdminClient : System.ServiceModel.ClientBase<WpfAdminPeritz.ServiceReferenceChess.IChessServiceAdmin>, WpfAdminPeritz.ServiceReferenceChess.IChessServiceAdmin {
        
        public ChessServiceAdminClient() {
        }
        
        public ChessServiceAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChessServiceAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChessServiceAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChessServiceAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.GameList GetAllGames() {
            return base.Channel.GetAllGames();
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.GameList> GetAllGamesAsync() {
            return base.Channel.GetAllGamesAsync();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game GetGameByID(int gameID) {
            return base.Channel.GetGameByID(gameID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> GetGameByIDAsync(int gameID) {
            return base.Channel.GetGameByIDAsync(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game InsertGame(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.InsertGame(game);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> InsertGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.InsertGameAsync(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game InsertGameAndReturn(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.InsertGameAndReturn(game);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> InsertGameAndReturnAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.InsertGameAndReturnAsync(game);
        }
        
        public void UpdateGame(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            base.Channel.UpdateGame(game);
        }
        
        public System.Threading.Tasks.Task UpdateGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.UpdateGameAsync(game);
        }
        
        public void UpdateGameResult(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            base.Channel.UpdateGameResult(game);
        }
        
        public System.Threading.Tasks.Task UpdateGameResultAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.UpdateGameResultAsync(game);
        }
        
        public void DeleteGame(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            base.Channel.DeleteGame(game);
        }
        
        public System.Threading.Tasks.Task DeleteGameAsync(WpfAdminPeritz.ServiceReferenceChess.Game game) {
            return base.Channel.DeleteGameAsync(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.GameList GetGamesByPlayer(int playerID) {
            return base.Channel.GetGamesByPlayer(playerID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.GameList> GetGamesByPlayerAsync(int playerID) {
            return base.Channel.GetGamesByPlayerAsync(playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Game GetLatestGameForPlayer(int playerID) {
            return base.Channel.GetLatestGameForPlayer(playerID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Game> GetLatestGameForPlayerAsync(int playerID) {
            return base.Channel.GetLatestGameForPlayerAsync(playerID);
        }
        
        public bool IsGameFinished(int gameID) {
            return base.Channel.IsGameFinished(gameID);
        }
        
        public System.Threading.Tasks.Task<bool> IsGameFinishedAsync(int gameID) {
            return base.Channel.IsGameFinishedAsync(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.GameList GetActiveGames() {
            return base.Channel.GetActiveGames();
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.GameList> GetActiveGamesAsync() {
            return base.Channel.GetActiveGamesAsync();
        }
        
        public void InsertMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            base.Channel.InsertMove(move);
        }
        
        public System.Threading.Tasks.Task InsertMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            return base.Channel.InsertMoveAsync(move);
        }
        
        public void UpdateMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            base.Channel.UpdateMove(move);
        }
        
        public System.Threading.Tasks.Task UpdateMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            return base.Channel.UpdateMoveAsync(move);
        }
        
        public void DeleteMove(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            base.Channel.DeleteMove(move);
        }
        
        public System.Threading.Tasks.Task DeleteMoveAsync(WpfAdminPeritz.ServiceReferenceChess.MoveRecord move) {
            return base.Channel.DeleteMoveAsync(move);
        }
        
        public void DeleteMovesByGameID(int gameID) {
            base.Channel.DeleteMovesByGameID(gameID);
        }
        
        public System.Threading.Tasks.Task DeleteMovesByGameIDAsync(int gameID) {
            return base.Channel.DeleteMovesByGameIDAsync(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveList GetAllMoves() {
            return base.Channel.GetAllMoves();
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveList> GetAllMovesAsync() {
            return base.Channel.GetAllMovesAsync();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByGameID(int gameID) {
            return base.Channel.GetMovesByGameID(gameID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveList> GetMovesByGameIDAsync(int gameID) {
            return base.Channel.GetMovesByGameIDAsync(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveList GetMovesByPlayerID(int playerID) {
            return base.Channel.GetMovesByPlayerID(playerID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveList> GetMovesByPlayerIDAsync(int playerID) {
            return base.Channel.GetMovesByPlayerIDAsync(playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveRecord ReturnLastMoveByGameID(int gameID) {
            return base.Channel.ReturnLastMoveByGameID(gameID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveRecord> ReturnLastMoveByGameIDAsync(int gameID) {
            return base.Channel.ReturnLastMoveByGameIDAsync(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.MoveRecord UndoLastMove(int gameID) {
            return base.Channel.UndoLastMove(gameID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.MoveRecord> UndoLastMoveAsync(int gameID) {
            return base.Channel.UndoLastMoveAsync(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.PlayerList GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.PlayerList> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Player GetUserByID(int userID) {
            return base.Channel.GetUserByID(userID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> GetUserByIDAsync(int userID) {
            return base.Channel.GetUserByIDAsync(userID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Player GetUserByName(string name) {
            return base.Channel.GetUserByName(name);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> GetUserByNameAsync(string name) {
            return base.Channel.GetUserByNameAsync(name);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.PlayerList SearchUsersByName(string name) {
            return base.Channel.SearchUsersByName(name);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.PlayerList> SearchUsersByNameAsync(string name) {
            return base.Channel.SearchUsersByNameAsync(name);
        }
        
        public void InsertUser(WpfAdminPeritz.ServiceReferenceChess.Player user) {
            base.Channel.InsertUser(user);
        }
        
        public System.Threading.Tasks.Task InsertUserAsync(WpfAdminPeritz.ServiceReferenceChess.Player user) {
            return base.Channel.InsertUserAsync(user);
        }
        
        public void UpdateUser(WpfAdminPeritz.ServiceReferenceChess.Player user) {
            base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(WpfAdminPeritz.ServiceReferenceChess.Player user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public void DeleteUser(WpfAdminPeritz.ServiceReferenceChess.Player user) {
            base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(WpfAdminPeritz.ServiceReferenceChess.Player user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public void UpdatePlayerStats(int playerID, bool won) {
            base.Channel.UpdatePlayerStats(playerID, won);
        }
        
        public System.Threading.Tasks.Task UpdatePlayerStatsAsync(int playerID, bool won) {
            return base.Channel.UpdatePlayerStatsAsync(playerID, won);
        }
        
        public void UpdatePlayerDraw(int playerID) {
            base.Channel.UpdatePlayerDraw(playerID);
        }
        
        public System.Threading.Tasks.Task UpdatePlayerDrawAsync(int playerID) {
            return base.Channel.UpdatePlayerDrawAsync(playerID);
        }
        
        public void RevertPlayerStats(int playerID, bool won) {
            base.Channel.RevertPlayerStats(playerID, won);
        }
        
        public System.Threading.Tasks.Task RevertPlayerStatsAsync(int playerID, bool won) {
            return base.Channel.RevertPlayerStatsAsync(playerID, won);
        }
        
        public void RevertPlayerDraw(int playerID) {
            base.Channel.RevertPlayerDraw(playerID);
        }
        
        public System.Threading.Tasks.Task RevertPlayerDrawAsync(int playerID) {
            return base.Channel.RevertPlayerDrawAsync(playerID);
        }
        
        public bool IsPlayerTurn(int gameID, int playerID) {
            return base.Channel.IsPlayerTurn(gameID, playerID);
        }
        
        public System.Threading.Tasks.Task<bool> IsPlayerTurnAsync(int gameID, int playerID) {
            return base.Channel.IsPlayerTurnAsync(gameID, playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.Player SignIn(string email, string password) {
            return base.Channel.SignIn(email, password);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.Player> SignInAsync(string email, string password) {
            return base.Channel.SignInAsync(email, password);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAllFriendships() {
            return base.Channel.GetAllFriendships();
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetAllFriendshipsAsync() {
            return base.Channel.GetAllFriendshipsAsync();
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetAcceptedFriendsByUser(int userID) {
            return base.Channel.GetAcceptedFriendsByUser(userID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetAcceptedFriendsByUserAsync(int userID) {
            return base.Channel.GetAcceptedFriendsByUserAsync(userID);
        }
        
        public WpfAdminPeritz.ServiceReferenceChess.FriendshipList GetPendingFriendRequestsForUser(int userID) {
            return base.Channel.GetPendingFriendRequestsForUser(userID);
        }
        
        public System.Threading.Tasks.Task<WpfAdminPeritz.ServiceReferenceChess.FriendshipList> GetPendingFriendRequestsForUserAsync(int userID) {
            return base.Channel.GetPendingFriendRequestsForUserAsync(userID);
        }
        
        public bool FriendshipExists(int userA, int userB) {
            return base.Channel.FriendshipExists(userA, userB);
        }
        
        public System.Threading.Tasks.Task<bool> FriendshipExistsAsync(int userA, int userB) {
            return base.Channel.FriendshipExistsAsync(userA, userB);
        }
        
        public int SendFriendRequest(int requesterID, int receiverID) {
            return base.Channel.SendFriendRequest(requesterID, receiverID);
        }
        
        public System.Threading.Tasks.Task<int> SendFriendRequestAsync(int requesterID, int receiverID) {
            return base.Channel.SendFriendRequestAsync(requesterID, receiverID);
        }
        
        public void AcceptFriendRequest(int friendshipID) {
            base.Channel.AcceptFriendRequest(friendshipID);
        }
        
        public System.Threading.Tasks.Task AcceptFriendRequestAsync(int friendshipID) {
            return base.Channel.AcceptFriendRequestAsync(friendshipID);
        }
        
        public void DeleteFriendship(int friendshipID) {
            base.Channel.DeleteFriendship(friendshipID);
        }
        
        public System.Threading.Tasks.Task DeleteFriendshipAsync(int friendshipID) {
            return base.Channel.DeleteFriendshipAsync(friendshipID);
        }
        
        public void DeclineFriendRequest(int friendshipID) {
            base.Channel.DeclineFriendRequest(friendshipID);
        }
        
        public System.Threading.Tasks.Task DeclineFriendRequestAsync(int friendshipID) {
            return base.Channel.DeclineFriendRequestAsync(friendshipID);
        }
    }
}
