//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAdminPeritz.ServiceReferenceUserChess
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="GameList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Game")]
    public class GameList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceUserChess.Game>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Game : WpfAdminPeritz.ServiceReferenceUserChess.BaseEntity
    {
        
        private WpfAdminPeritz.ServiceReferenceUserChess.Player BlackPlayerField;
        
        private WpfAdminPeritz.ServiceReferenceUserChess.Player BlackPlayerUserIDField;
        
        private System.DateTime GameDateField;
        
        private int GameIDField;
        
        private WpfAdminPeritz.ServiceReferenceUserChess.Player ResultField;
        
        private WpfAdminPeritz.ServiceReferenceUserChess.Player WhitePlayerField;
        
        private WpfAdminPeritz.ServiceReferenceUserChess.Player WhitePlayerUserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceUserChess.Player BlackPlayer
        {
            get
            {
                return this.BlackPlayerField;
            }
            set
            {
                this.BlackPlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceUserChess.Player BlackPlayerUserID
        {
            get
            {
                return this.BlackPlayerUserIDField;
            }
            set
            {
                this.BlackPlayerUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GameDate
        {
            get
            {
                return this.GameDateField;
            }
            set
            {
                this.GameDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID
        {
            get
            {
                return this.GameIDField;
            }
            set
            {
                this.GameIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceUserChess.Player Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceUserChess.Player WhitePlayer
        {
            get
            {
                return this.WhitePlayerField;
            }
            set
            {
                this.WhitePlayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceUserChess.Player WhitePlayerUserID
        {
            get
            {
                return this.WhitePlayerUserIDField;
            }
            set
            {
                this.WhitePlayerUserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceUserChess.Player))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceUserChess.Friendship))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfAdminPeritz.ServiceReferenceUserChess.Game))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Player : WpfAdminPeritz.ServiceReferenceUserChess.BaseEntity
    {
        
        private System.DateTime DateJoinedField;
        
        private int DrawsField;
        
        private string EmailField;
        
        private int GamesPlayedField;
        
        private string GoogleIdField;
        
        private int LossesField;
        
        private string UserNameField;
        
        private string UserTypeField;
        
        private int WinsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateJoined
        {
            get
            {
                return this.DateJoinedField;
            }
            set
            {
                this.DateJoinedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Draws
        {
            get
            {
                return this.DrawsField;
            }
            set
            {
                this.DrawsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GamesPlayed
        {
            get
            {
                return this.GamesPlayedField;
            }
            set
            {
                this.GamesPlayedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleId
        {
            get
            {
                return this.GoogleIdField;
            }
            set
            {
                this.GoogleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Losses
        {
            get
            {
                return this.LossesField;
            }
            set
            {
                this.LossesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins
        {
            get
            {
                return this.WinsField;
            }
            set
            {
                this.WinsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoveRecord", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class MoveRecord : WpfAdminPeritz.ServiceReferenceUserChess.BaseEntity
    {
        
        private string FromField;
        
        private WpfAdminPeritz.ServiceReferenceUserChess.Game GameField;
        
        private int GameIDField;
        
        private int MoveIndexField;
        
        private string MoveTypeField;
        
        private string PromotionField;
        
        private string ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAdminPeritz.ServiceReferenceUserChess.Game Game
        {
            get
            {
                return this.GameField;
            }
            set
            {
                this.GameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID
        {
            get
            {
                return this.GameIDField;
            }
            set
            {
                this.GameIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MoveIndex
        {
            get
            {
                return this.MoveIndexField;
            }
            set
            {
                this.MoveIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoveType
        {
            get
            {
                return this.MoveTypeField;
            }
            set
            {
                this.MoveTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Promotion
        {
            get
            {
                return this.PromotionField;
            }
            set
            {
                this.PromotionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Friendship", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Friendship : WpfAdminPeritz.ServiceReferenceUserChess.BaseEntity
    {
        
        private System.Nullable<System.DateTime> FriendshipDateField;
        
        private bool IsAcceptedField;
        
        private int ReceiverIDField;
        
        private int RequesterIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FriendshipDate
        {
            get
            {
                return this.FriendshipDateField;
            }
            set
            {
                this.FriendshipDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAccepted
        {
            get
            {
                return this.IsAcceptedField;
            }
            set
            {
                this.IsAcceptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiverID
        {
            get
            {
                return this.ReceiverIDField;
            }
            set
            {
                this.ReceiverIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequesterID
        {
            get
            {
                return this.RequesterIDField;
            }
            set
            {
                this.RequesterIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PlayerList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Player")]
    public class PlayerList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceUserChess.Player>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MoveList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="MoveRecord")]
    public class MoveList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FriendshipList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Friendship")]
    public class FriendshipList : System.Collections.Generic.List<WpfAdminPeritz.ServiceReferenceUserChess.Friendship>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WpfAdminPeritz.ServiceReferenceUserChess.IChessServiceUser", CallbackContract=typeof(WpfAdminPeritz.ServiceReferenceUserChess.IChessServiceUserCallback))]
    public interface IChessServiceUser
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetAllGames", ReplyAction="http://tempuri.org/IChessServiceUser/GetAllGamesResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.GameList GetAllGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetActiveGames", ReplyAction="http://tempuri.org/IChessServiceUser/GetActiveGamesResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.GameList GetActiveGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetGameByID", ReplyAction="http://tempuri.org/IChessServiceUser/GetGameByIDResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.Game GetGameByID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetGameByIDWithGame", ReplyAction="http://tempuri.org/IChessServiceUser/GetGameByIDWithGameResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.Game GetGameByIDWithGame(WpfAdminPeritz.ServiceReferenceUserChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/InsertGame", ReplyAction="http://tempuri.org/IChessServiceUser/InsertGameResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.Game InsertGame(WpfAdminPeritz.ServiceReferenceUserChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/InsertGameAndReturn", ReplyAction="http://tempuri.org/IChessServiceUser/InsertGameAndReturnResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.Game InsertGameAndReturn(WpfAdminPeritz.ServiceReferenceUserChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/UpdateGame", ReplyAction="http://tempuri.org/IChessServiceUser/UpdateGameResponse")]
        void UpdateGame(WpfAdminPeritz.ServiceReferenceUserChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/UpdateGameResult", ReplyAction="http://tempuri.org/IChessServiceUser/UpdateGameResultResponse")]
        void UpdateGameResult(WpfAdminPeritz.ServiceReferenceUserChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/DeleteGame", ReplyAction="http://tempuri.org/IChessServiceUser/DeleteGameResponse")]
        void DeleteGame(WpfAdminPeritz.ServiceReferenceUserChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/DeleteOpen", ReplyAction="http://tempuri.org/IChessServiceUser/DeleteOpenResponse")]
        void DeleteOpen(WpfAdminPeritz.ServiceReferenceUserChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetGamesByPlayer", ReplyAction="http://tempuri.org/IChessServiceUser/GetGamesByPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.GameList GetGamesByPlayer(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetGamesByPlayerWithPlayer", ReplyAction="http://tempuri.org/IChessServiceUser/GetGamesByPlayerWithPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.GameList GetGamesByPlayerWithPlayer(WpfAdminPeritz.ServiceReferenceUserChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetLatestGameForPlayer", ReplyAction="http://tempuri.org/IChessServiceUser/GetLatestGameForPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.Game GetLatestGameForPlayer(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/IsGameFinished", ReplyAction="http://tempuri.org/IChessServiceUser/IsGameFinishedResponse")]
        bool IsGameFinished(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetAllUsers", ReplyAction="http://tempuri.org/IChessServiceUser/GetAllUsersResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.PlayerList GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetAllplayers", ReplyAction="http://tempuri.org/IChessServiceUser/GetAllplayersResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.PlayerList GetAllplayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetUserByID", ReplyAction="http://tempuri.org/IChessServiceUser/GetUserByIDResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.Player GetUserByID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/InsertUser", ReplyAction="http://tempuri.org/IChessServiceUser/InsertUserResponse")]
        void InsertUser(WpfAdminPeritz.ServiceReferenceUserChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/InsertPlayer", ReplyAction="http://tempuri.org/IChessServiceUser/InsertPlayerResponse")]
        void InsertPlayer(WpfAdminPeritz.ServiceReferenceUserChess.Player player, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/UpdateUser", ReplyAction="http://tempuri.org/IChessServiceUser/UpdateUserResponse")]
        void UpdateUser(WpfAdminPeritz.ServiceReferenceUserChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/DeleteUser", ReplyAction="http://tempuri.org/IChessServiceUser/DeleteUserResponse")]
        void DeleteUser(WpfAdminPeritz.ServiceReferenceUserChess.Player user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/InsertMove", ReplyAction="http://tempuri.org/IChessServiceUser/InsertMoveResponse")]
        void InsertMove(WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/UpdateMove", ReplyAction="http://tempuri.org/IChessServiceUser/UpdateMoveResponse")]
        void UpdateMove(WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/DeleteMove", ReplyAction="http://tempuri.org/IChessServiceUser/DeleteMoveResponse")]
        void DeleteMove(WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetMovesByGameID", ReplyAction="http://tempuri.org/IChessServiceUser/GetMovesByGameIDResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.MoveList GetMovesByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetMovesByPlayerID", ReplyAction="http://tempuri.org/IChessServiceUser/GetMovesByPlayerIDResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.MoveList GetMovesByPlayerID(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetMoveByID", ReplyAction="http://tempuri.org/IChessServiceUser/GetMoveByIDResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord GetMoveByID(int moveID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetLastMoveByGameID", ReplyAction="http://tempuri.org/IChessServiceUser/GetLastMoveByGameIDResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord GetLastMoveByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/ReturnLastMoveByGameID", ReplyAction="http://tempuri.org/IChessServiceUser/ReturnLastMoveByGameIDResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord ReturnLastMoveByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/UndoLastMove", ReplyAction="http://tempuri.org/IChessServiceUser/UndoLastMoveResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord UndoLastMove(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/IsPlayerTurn", ReplyAction="http://tempuri.org/IChessServiceUser/IsPlayerTurnResponse")]
        bool IsPlayerTurn(int gameID, int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/UpdatePlayerStats", ReplyAction="http://tempuri.org/IChessServiceUser/UpdatePlayerStatsResponse")]
        void UpdatePlayerStats(int playerID, bool won);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/UpdatePlayerDraw", ReplyAction="http://tempuri.org/IChessServiceUser/UpdatePlayerDrawResponse")]
        void UpdatePlayerDraw(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/SignUp", ReplyAction="http://tempuri.org/IChessServiceUser/SignUpResponse")]
        string SignUp(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/Login", ReplyAction="http://tempuri.org/IChessServiceUser/LoginResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.Player Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/PlayerJoin", ReplyAction="http://tempuri.org/IChessServiceUser/PlayerJoinResponse")]
        void PlayerJoin(WpfAdminPeritz.ServiceReferenceUserChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/PlayerLeave", ReplyAction="http://tempuri.org/IChessServiceUser/PlayerLeaveResponse")]
        void PlayerLeave(WpfAdminPeritz.ServiceReferenceUserChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetOnlinePlayers", ReplyAction="http://tempuri.org/IChessServiceUser/GetOnlinePlayersResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.PlayerList GetOnlinePlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/InvitePlayer", ReplyAction="http://tempuri.org/IChessServiceUser/InvitePlayerResponse")]
        void InvitePlayer(WpfAdminPeritz.ServiceReferenceUserChess.Player inviter, WpfAdminPeritz.ServiceReferenceUserChess.Player invited, bool isWhite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/RespondToInvitation", ReplyAction="http://tempuri.org/IChessServiceUser/RespondToInvitationResponse")]
        void RespondToInvitation(WpfAdminPeritz.ServiceReferenceUserChess.Player inviter, WpfAdminPeritz.ServiceReferenceUserChess.Player invited, bool accept, bool isWhite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/SendMove", ReplyAction="http://tempuri.org/IChessServiceUser/SendMoveResponse")]
        void SendMove(WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/LeaveGame", ReplyAction="http://tempuri.org/IChessServiceUser/LeaveGameResponse")]
        void LeaveGame(WpfAdminPeritz.ServiceReferenceUserChess.Game game, WpfAdminPeritz.ServiceReferenceUserChess.Player leavingPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetAcceptedFriendsByPlayer", ReplyAction="http://tempuri.org/IChessServiceUser/GetAcceptedFriendsByPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.FriendshipList GetAcceptedFriendsByPlayer(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetAcceptedFriendsByPlayerWithPlayer", ReplyAction="http://tempuri.org/IChessServiceUser/GetAcceptedFriendsByPlayerWithPlayerResponse" +
            "")]
        WpfAdminPeritz.ServiceReferenceUserChess.FriendshipList GetAcceptedFriendsByPlayerWithPlayer(WpfAdminPeritz.ServiceReferenceUserChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetPendingFriendRequestsForPlayer", ReplyAction="http://tempuri.org/IChessServiceUser/GetPendingFriendRequestsForPlayerResponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.FriendshipList GetPendingFriendRequestsForPlayer(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/GetPendingFriendRequestsForPlayerWithPlayer", ReplyAction="http://tempuri.org/IChessServiceUser/GetPendingFriendRequestsForPlayerWithPlayerR" +
            "esponse")]
        WpfAdminPeritz.ServiceReferenceUserChess.FriendshipList GetPendingFriendRequestsForPlayerWithPlayer(WpfAdminPeritz.ServiceReferenceUserChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/FriendshipExists", ReplyAction="http://tempuri.org/IChessServiceUser/FriendshipExistsResponse")]
        bool FriendshipExists(int userA, int userB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/SendFriendRequest", ReplyAction="http://tempuri.org/IChessServiceUser/SendFriendRequestResponse")]
        int SendFriendRequest(int requesterID, int receiverID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/SendFriendRequestWithObject", ReplyAction="http://tempuri.org/IChessServiceUser/SendFriendRequestWithObjectResponse")]
        int SendFriendRequestWithObject(WpfAdminPeritz.ServiceReferenceUserChess.Friendship friendship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/AcceptFriendRequest", ReplyAction="http://tempuri.org/IChessServiceUser/AcceptFriendRequestResponse")]
        void AcceptFriendRequest(int friendshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/AcceptFriendRequestWithObject", ReplyAction="http://tempuri.org/IChessServiceUser/AcceptFriendRequestWithObjectResponse")]
        void AcceptFriendRequestWithObject(WpfAdminPeritz.ServiceReferenceUserChess.Friendship friendship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/DeleteFriendship", ReplyAction="http://tempuri.org/IChessServiceUser/DeleteFriendshipResponse")]
        void DeleteFriendship(int friendshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/DeleteFriendshipWithObject", ReplyAction="http://tempuri.org/IChessServiceUser/DeleteFriendshipWithObjectResponse")]
        void DeleteFriendshipWithObject(WpfAdminPeritz.ServiceReferenceUserChess.Friendship friendship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/DeclineFriendRequest", ReplyAction="http://tempuri.org/IChessServiceUser/DeclineFriendRequestResponse")]
        void DeclineFriendRequest(int friendshipID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChessServiceUser/DeclineFriendRequestWithObject", ReplyAction="http://tempuri.org/IChessServiceUser/DeclineFriendRequestWithObjectResponse")]
        void DeclineFriendRequestWithObject(WpfAdminPeritz.ServiceReferenceUserChess.Friendship friendship);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChessServiceUserCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChessServiceUser/PlayerJoined")]
        void PlayerJoined(WpfAdminPeritz.ServiceReferenceUserChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChessServiceUser/PlayerLeft")]
        void PlayerLeft(WpfAdminPeritz.ServiceReferenceUserChess.Player player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChessServiceUser/RecievedMove")]
        void RecievedMove(WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord move);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChessServiceUser/RecieveInvitation")]
        void RecieveInvitation(WpfAdminPeritz.ServiceReferenceUserChess.Player inviter, bool isWhite);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChessServiceUser/RecieveInvitationResponse")]
        void RecieveInvitationResponse(WpfAdminPeritz.ServiceReferenceUserChess.Player inviter, bool accept, WpfAdminPeritz.ServiceReferenceUserChess.Game game);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChessServiceUser/OpponentLeftGame")]
        void OpponentLeftGame();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChessServiceUserChannel : WpfAdminPeritz.ServiceReferenceUserChess.IChessServiceUser, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChessServiceUserClient : System.ServiceModel.DuplexClientBase<WpfAdminPeritz.ServiceReferenceUserChess.IChessServiceUser>, WpfAdminPeritz.ServiceReferenceUserChess.IChessServiceUser
    {
        
        public ChessServiceUserClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance)
        {
        }
        
        public ChessServiceUserClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName)
        {
        }
        
        public ChessServiceUserClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public ChessServiceUserClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public ChessServiceUserClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.GameList GetAllGames()
        {
            return base.Channel.GetAllGames();
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.GameList GetActiveGames()
        {
            return base.Channel.GetActiveGames();
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.Game GetGameByID(int gameID)
        {
            return base.Channel.GetGameByID(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.Game GetGameByIDWithGame(WpfAdminPeritz.ServiceReferenceUserChess.Game game)
        {
            return base.Channel.GetGameByIDWithGame(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.Game InsertGame(WpfAdminPeritz.ServiceReferenceUserChess.Game game)
        {
            return base.Channel.InsertGame(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.Game InsertGameAndReturn(WpfAdminPeritz.ServiceReferenceUserChess.Game game)
        {
            return base.Channel.InsertGameAndReturn(game);
        }
        
        public void UpdateGame(WpfAdminPeritz.ServiceReferenceUserChess.Game game)
        {
            base.Channel.UpdateGame(game);
        }
        
        public void UpdateGameResult(WpfAdminPeritz.ServiceReferenceUserChess.Game game)
        {
            base.Channel.UpdateGameResult(game);
        }
        
        public void DeleteGame(WpfAdminPeritz.ServiceReferenceUserChess.Game game)
        {
            base.Channel.DeleteGame(game);
        }
        
        public void DeleteOpen(WpfAdminPeritz.ServiceReferenceUserChess.Game game)
        {
            base.Channel.DeleteOpen(game);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.GameList GetGamesByPlayer(int playerID)
        {
            return base.Channel.GetGamesByPlayer(playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.GameList GetGamesByPlayerWithPlayer(WpfAdminPeritz.ServiceReferenceUserChess.Player player)
        {
            return base.Channel.GetGamesByPlayerWithPlayer(player);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.Game GetLatestGameForPlayer(int playerID)
        {
            return base.Channel.GetLatestGameForPlayer(playerID);
        }
        
        public bool IsGameFinished(int gameID)
        {
            return base.Channel.IsGameFinished(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.PlayerList GetAllUsers()
        {
            return base.Channel.GetAllUsers();
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.PlayerList GetAllplayers()
        {
            return base.Channel.GetAllplayers();
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.Player GetUserByID(int userID)
        {
            return base.Channel.GetUserByID(userID);
        }
        
        public void InsertUser(WpfAdminPeritz.ServiceReferenceUserChess.Player user)
        {
            base.Channel.InsertUser(user);
        }
        
        public void InsertPlayer(WpfAdminPeritz.ServiceReferenceUserChess.Player player, string password)
        {
            base.Channel.InsertPlayer(player, password);
        }
        
        public void UpdateUser(WpfAdminPeritz.ServiceReferenceUserChess.Player user)
        {
            base.Channel.UpdateUser(user);
        }
        
        public void DeleteUser(WpfAdminPeritz.ServiceReferenceUserChess.Player user)
        {
            base.Channel.DeleteUser(user);
        }
        
        public void InsertMove(WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord move)
        {
            base.Channel.InsertMove(move);
        }
        
        public void UpdateMove(WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord move)
        {
            base.Channel.UpdateMove(move);
        }
        
        public void DeleteMove(WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord move)
        {
            base.Channel.DeleteMove(move);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.MoveList GetMovesByGameID(int gameID)
        {
            return base.Channel.GetMovesByGameID(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.MoveList GetMovesByPlayerID(int playerID)
        {
            return base.Channel.GetMovesByPlayerID(playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord GetMoveByID(int moveID)
        {
            return base.Channel.GetMoveByID(moveID);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord GetLastMoveByGameID(int gameID)
        {
            return base.Channel.GetLastMoveByGameID(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord ReturnLastMoveByGameID(int gameID)
        {
            return base.Channel.ReturnLastMoveByGameID(gameID);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord UndoLastMove(int gameID)
        {
            return base.Channel.UndoLastMove(gameID);
        }
        
        public bool IsPlayerTurn(int gameID, int playerID)
        {
            return base.Channel.IsPlayerTurn(gameID, playerID);
        }
        
        public void UpdatePlayerStats(int playerID, bool won)
        {
            base.Channel.UpdatePlayerStats(playerID, won);
        }
        
        public void UpdatePlayerDraw(int playerID)
        {
            base.Channel.UpdatePlayerDraw(playerID);
        }
        
        public string SignUp(string email, string password)
        {
            return base.Channel.SignUp(email, password);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.Player Login(string email, string password)
        {
            return base.Channel.Login(email, password);
        }
        
        public void PlayerJoin(WpfAdminPeritz.ServiceReferenceUserChess.Player player)
        {
            base.Channel.PlayerJoin(player);
        }
        
        public void PlayerLeave(WpfAdminPeritz.ServiceReferenceUserChess.Player player)
        {
            base.Channel.PlayerLeave(player);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.PlayerList GetOnlinePlayers()
        {
            return base.Channel.GetOnlinePlayers();
        }
        
        public void InvitePlayer(WpfAdminPeritz.ServiceReferenceUserChess.Player inviter, WpfAdminPeritz.ServiceReferenceUserChess.Player invited, bool isWhite)
        {
            base.Channel.InvitePlayer(inviter, invited, isWhite);
        }
        
        public void RespondToInvitation(WpfAdminPeritz.ServiceReferenceUserChess.Player inviter, WpfAdminPeritz.ServiceReferenceUserChess.Player invited, bool accept, bool isWhite)
        {
            base.Channel.RespondToInvitation(inviter, invited, accept, isWhite);
        }
        
        public void SendMove(WpfAdminPeritz.ServiceReferenceUserChess.MoveRecord move)
        {
            base.Channel.SendMove(move);
        }
        
        public void LeaveGame(WpfAdminPeritz.ServiceReferenceUserChess.Game game, WpfAdminPeritz.ServiceReferenceUserChess.Player leavingPlayer)
        {
            base.Channel.LeaveGame(game, leavingPlayer);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.FriendshipList GetAcceptedFriendsByPlayer(int playerID)
        {
            return base.Channel.GetAcceptedFriendsByPlayer(playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.FriendshipList GetAcceptedFriendsByPlayerWithPlayer(WpfAdminPeritz.ServiceReferenceUserChess.Player player)
        {
            return base.Channel.GetAcceptedFriendsByPlayerWithPlayer(player);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.FriendshipList GetPendingFriendRequestsForPlayer(int playerID)
        {
            return base.Channel.GetPendingFriendRequestsForPlayer(playerID);
        }
        
        public WpfAdminPeritz.ServiceReferenceUserChess.FriendshipList GetPendingFriendRequestsForPlayerWithPlayer(WpfAdminPeritz.ServiceReferenceUserChess.Player player)
        {
            return base.Channel.GetPendingFriendRequestsForPlayerWithPlayer(player);
        }
        
        public bool FriendshipExists(int userA, int userB)
        {
            return base.Channel.FriendshipExists(userA, userB);
        }
        
        public int SendFriendRequest(int requesterID, int receiverID)
        {
            return base.Channel.SendFriendRequest(requesterID, receiverID);
        }
        
        public int SendFriendRequestWithObject(WpfAdminPeritz.ServiceReferenceUserChess.Friendship friendship)
        {
            return base.Channel.SendFriendRequestWithObject(friendship);
        }
        
        public void AcceptFriendRequest(int friendshipID)
        {
            base.Channel.AcceptFriendRequest(friendshipID);
        }
        
        public void AcceptFriendRequestWithObject(WpfAdminPeritz.ServiceReferenceUserChess.Friendship friendship)
        {
            base.Channel.AcceptFriendRequestWithObject(friendship);
        }
        
        public void DeleteFriendship(int friendshipID)
        {
            base.Channel.DeleteFriendship(friendshipID);
        }
        
        public void DeleteFriendshipWithObject(WpfAdminPeritz.ServiceReferenceUserChess.Friendship friendship)
        {
            base.Channel.DeleteFriendshipWithObject(friendship);
        }
        
        public void DeclineFriendRequest(int friendshipID)
        {
            base.Channel.DeclineFriendRequest(friendshipID);
        }
        
        public void DeclineFriendRequestWithObject(WpfAdminPeritz.ServiceReferenceUserChess.Friendship friendship)
        {
            base.Channel.DeclineFriendRequestWithObject(friendship);
        }
    }
}
